In [1]:
import numpy as np
from pandas import read_csv
# np.genfromtxt('/Users/zhangmengqiao/Desktop/StatiscalAnalysis.csv',delimiter=",",skip_header = 1)
data = read_csv('/Users/zhangmengqiao/Desktop/StatiscalAnalysis.csv',delimiter=",",skiprows = 0)
data = data.as_matrix()
X = data[:, 2:]
y = data[:, 0].astype(int)

In [2]:
from sklearn.cross_validation import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import linear_model
from sklearn import svm
from sklearn.feature_selection import VarianceThreshold
from sklearn import preprocessing

# X = preprocessing.normalize(X, norm='l2')
# X = VarianceThreshold(threshold=1).fit_transform(X)
# print(X.shape)

# scores = cross_val_score(KNeighborsClassifier(n_neighbors=3), X, y, cv=5, scoring='accuracy')
# scores = cross_val_score(svm.SVC(kernel='linear', C=1), X, y, cv=5, scoring='accuracy')


# print(scores)

# print(scores.mean())
# np.var(X, axis=0)

//anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [3]:
from sklearn.tree import DecisionTreeClassifier
scores = cross_val_score(DecisionTreeClassifier(criterion='gini', max_depth=7, random_state=0)
, X, y, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[ 0.75        0.52631579  0.55555556  0.70588235  0.70588235]
0.648727210182


In [16]:
from sklearn.neighbors import KNeighborsClassifier
scores = cross_val_score(KNeighborsClassifier(n_neighbors=3), X, y, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[ 0.65        0.42105263  0.5         0.58823529  0.64705882]
0.561269349845


In [74]:
from sklearn.linear_model import LogisticRegression
scores = cross_val_score(LogisticRegression(C=30, random_state=0), X, y, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[ 0.75        0.84210526  0.66666667  0.82352941  0.58823529]
0.734107327141


In [34]:
from sklearn import svm
scores = cross_val_score(svm.SVC(C=1.0, decision_function_shape='ovo',kernel='rbf'), X, y, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[ 0.25        0.26315789  0.27777778  0.29411765  0.29411765]
0.275834193326


In [78]:
from sklearn.cluster import KMeans
scores = cross_val_score(KMeans(n_clusters=4, random_state=0), X, y, cv=5, scoring='v_measure_score')
print(scores)
print(scores.mean())

[ -1.61791926e-15   5.40261252e-02   2.59334185e-01   1.19994903e-01
  -1.10230413e-15]
0.0866710425044
